:lang: ja
:doctype: book

= ソケットプログラミング課題
ネットワーク上のマシンAからマシンBへ、ソケット経由でファイル転送を行うプログラムを作成せよ

== usage
サーバ起動
trans-data-server -p port [-s files-store-directory] [-d]
-p: 起動ポート番号
-s: 転送されたファイルを格納するディレクトリのパス
-d: デバッグモードを有効にする

サーバ停止
trans-data-client -t

ファイル転送
trans-data-client -h hostname -p port -f filename [-d]
-h: サーバのホスト名 or IP address
-p: サーバが起動しているポート番号
-f: 転送するファイルのパス
-d: デバッグモードを有効にする


== デバッグモード
デバッグモードを有効にした場合は、サーバは実行ログを「trans-data-server.pid」に出力する。
クライアントは標準出力にログを出力する。
サーバはデーモン化する関係で制御端末を切り離すためファイル出力により対応するが、
クライアントはデーモン化しないのとユーザビリティの観点から標準出力にログを出力する。

出力フォーマットは以下のように先頭からLINEまでをヘッダとし、ここは90バイトの左詰め。
また、ヘッダ+メッセージを合わせて512バイトにする。

----
yyyy/mm/dd HH/MM/SS.nsec thread_id FILENAME:LINE message
----


== マルチクライアント対応
サーバが同時に複数のクライアントからファイルを受信できるようにするため、
サーバ側はマルチスレッドで実装する。

=== 複数クライアントから同名のファイルを送られた場合
複数のクライアントから同時に同名のファイルを送信された場合、ファイル内容が破壊されてしまうため、
サーバ側は受信ファイルのオープン前に対象ファイルのファイルロックを取得する。
ロックファイル名は「ファイル名.lock」とし、lockf(2)によるアドバイザリロックを使ってファイルロックを取得する。
受信完了後は、ロックファイルは削除する。
ロックを取得できなかった場合は、クライアント側にエラーを返し終了する。


== 終了処理
クライアントから終了メッセージを受け取った場合、サーバは終了フラグを立ててクライアントに返答する。
実際の終了は、すべてのクライアントが通信を終えた後。

== メッセージシーケンス

== タイムアウト
ネットワークを介したファイル転送を行うため、通信環境によっては接続断などが発生する可能性があるため、
受信タイムアウトと接続タイムアウト機能を実装する。

=== 受信タイムアウト
一定の時間recv(2)がブロックした場合のタイムアウト。
外部ファイルからユーザが任意に設定できるのが理想ではあるが、今回は簡略化のため「20秒」の固定値とする。

=== 接続タイムアウト
クライアントからサーバへの通信確立を行う際のタイムアウト。
外部ファイルからユーザが任意に設定できるのが理想ではあるが、今回は簡略化のため「20秒」の固定値とする。 

== シグナルの扱い




